# Generated by Django 5.1.4 on 2024-12-30 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goals", "0002_initial"),
        ("standards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="standard",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="standardcategory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standard_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="standard",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standards",
                to="standards.standardcategory",
            ),
        ),
        migrations.AddField(
            model_name="standardprogress",
            name="daily_progress",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standard_progress",
                to="goals.dailyprogress",
            ),
        ),
        migrations.AddField(
            model_name="standardprogress",
            name="standard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to="standards.standard",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="standardcategory",
            unique_together={("user", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="standardprogress",
            unique_together={("daily_progress", "standard")},
        ),
    ]
